### ISSUE TITLE
您好！

### ISSUE THREAD

**Issue by Planet-Hunter** [emicoto/_Cursed-Isil#1]
封装的bat好像有点问题，缺少部署环境，我试了一下应该是tweego，另外，我在discord里留了言

**Comment by emicoto** [comment]
tweego原来是分开放的…
已经补上啦！

**Comment by Planet-Hunter** [comment]
好的，感谢。




对长亭晚
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emicoto/_Cursed-Isil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月16日(星期一) 凌晨1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [emicoto/_Cursed-Isil] 您好！ (Issue #1)





 
tweego原来是分开放的…
 已经补上啦！
